"""cliente alteração

Revision ID: 241bd9c504d4
Revises: de363aeb0549
Create Date: 2025-08-25 21:24:37.533202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '241bd9c504d4'
down_revision = 'de363aeb0549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
        batch_op.alter_column('rg',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
        batch_op.alter_column('telefone',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('logradouro',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('numero',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('cep',
               existing_type=sa.VARCHAR(length=8),
               nullable=True)
        batch_op.alter_column('municipio',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
        batch_op.alter_column('pais',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('pais',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
        batch_op.alter_column('municipio',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('cep',
               existing_type=sa.VARCHAR(length=8),
               nullable=False)
        batch_op.alter_column('numero',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('logradouro',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('telefone',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('rg',
               existing_type=sa.VARCHAR(length=9),
               nullable=False)
        batch_op.alter_column('cpf',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)

    # ### end Alembic commands ###
