"""bairro em clientes

Revision ID: 75d9cfe0125b
Revises: 8f7c9b2d6695
Create Date: 2025-06-30 19:23:50.632616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d9cfe0125b'
down_revision = '8f7c9b2d6695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bairro', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('bairro')

    # ### end Alembic commands ###
