"""ajuste

Revision ID: 8f7c9b2d6695
Revises: c753db40e4e2
Create Date: 2025-06-27 19:05:01.755816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f7c9b2d6695'
down_revision = 'c753db40e4e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preco_tabelado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hospedagem', sa.String(length=150), nullable=False))
        batch_op.alter_column('single',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('duplo',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('triplo',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('quadruplo',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('chd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.drop_constraint('preco_tabelado_hospedagem_id_fkey', type_='foreignkey')
        batch_op.drop_column('hospedagem_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preco_tabelado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hospedagem_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('preco_tabelado_hospedagem_id_fkey', 'hospedagens', ['hospedagem_id'], ['id'])
        batch_op.alter_column('chd',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('quadruplo',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('triplo',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('duplo',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('single',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.drop_column('hospedagem')

    # ### end Alembic commands ###
