"""cliente alteração

Revision ID: acf22cd76427
Revises: 241bd9c504d4
Create Date: 2025-08-25 21:38:02.125901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acf22cd76427'
down_revision = '241bd9c504d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_constraint('clientes_cpf_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_unique_constraint('clientes_cpf_key', ['cpf'])

    # ### end Alembic commands ###
