"""Migração inicial

Revision ID: aeb298d6fee9
Revises: 
Create Date: 2025-06-25 20:42:20.380110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeb298d6fee9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('rg', sa.String(length=9), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('data_nasc', sa.Date(), nullable=True),
    sa.Column('logradouro', sa.String(length=150), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('complemento', sa.String(length=50), nullable=True),
    sa.Column('cep', sa.String(length=8), nullable=False),
    sa.Column('municipio', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('pais', sa.String(length=20), nullable=False),
    sa.Column('observacao', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('hospedagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=False),
    sa.Column('endereco', sa.String(length=150), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relatorio_reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('total_mes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_ano', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reservas_mes', sa.Integer(), nullable=True),
    sa.Column('reservas_ano', sa.Integer(), nullable=True),
    sa.Column('total_adultos', sa.Integer(), nullable=True),
    sa.Column('total_criancas', sa.Integer(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('notas', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('roles', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('grupos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('data_ida', sa.Date(), nullable=False),
    sa.Column('data_volta', sa.Date(), nullable=False),
    sa.Column('horario_chegada', sa.Time(), nullable=True),
    sa.Column('horario_partida', sa.Time(), nullable=True),
    sa.Column('hospedagem_id', sa.Integer(), nullable=False),
    sa.Column('nome_hospedagem', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['hospedagem_id'], ['hospedagens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preco_tabelado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('single', sa.Float(), nullable=False),
    sa.Column('duplo', sa.Float(), nullable=False),
    sa.Column('triplo', sa.Float(), nullable=False),
    sa.Column('quadruplo', sa.Float(), nullable=False),
    sa.Column('chd', sa.Float(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hospedagem_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hospedagem_id'], ['hospedagens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupo_apartamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('id_grupo', sa.String(length=10), nullable=True),
    sa.Column('tipo_apart', sa.String(length=30), nullable=False),
    sa.Column('qtd_apart', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_reserva', sa.String(length=10), nullable=False),
    sa.Column('tipo_reserva', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nome_cliente', sa.String(length=100), nullable=True),
    sa.Column('opcoes_pacote', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('num_adultos', sa.Integer(), nullable=False),
    sa.Column('num_criancas', sa.Integer(), nullable=False),
    sa.Column('num_criancas_free', sa.Integer(), nullable=False),
    sa.Column('confirmada_por', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('pensao', sa.String(length=20), nullable=True),
    sa.Column('garante_no_show', sa.Boolean(), nullable=False),
    sa.Column('evento', sa.Boolean(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('grupo_id', sa.Integer(), nullable=True),
    sa.Column('nome_grupo', sa.String(length=100), nullable=True),
    sa.Column('nome_hospedagem_grupo', sa.String(length=100), nullable=True),
    sa.Column('hospedagem_id_grupo', sa.Integer(), nullable=True),
    sa.Column('tipo_apart_grupo', sa.String(length=100), nullable=True),
    sa.Column('companhia', sa.String(length=100), nullable=True),
    sa.Column('numero_voo', sa.String(length=20), nullable=True),
    sa.Column('data_ida', sa.Date(), nullable=True),
    sa.Column('data_volta', sa.Date(), nullable=True),
    sa.Column('horario_ida', sa.Time(), nullable=True),
    sa.Column('horario_chegada', sa.Time(), nullable=True),
    sa.Column('origem', sa.String(length=100), nullable=True),
    sa.Column('destino', sa.String(length=100), nullable=True),
    sa.Column('escala', sa.String(length=100), nullable=True),
    sa.Column('inclui_bagagem', sa.Boolean(), nullable=True),
    sa.Column('hospedagem_id', sa.Integer(), nullable=True),
    sa.Column('nome_hospedagem', sa.String(length=100), nullable=True),
    sa.Column('tipo_apart', sa.String(length=100), nullable=True),
    sa.Column('transporte_info', sa.Text(), nullable=True),
    sa.Column('seguro_info', sa.Text(), nullable=True),
    sa.Column('servico_info', sa.Text(), nullable=True),
    sa.Column('diaria', sa.Float(), nullable=True),
    sa.Column('diaria_pessoa', sa.Float(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.Column('depositos_confirmados', sa.Float(), nullable=True),
    sa.Column('lucro', sa.Float(), nullable=True),
    sa.Column('data_reserva', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hospedagem_id'], ['hospedagens.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospedes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reserva_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['reserva_id'], ['reservas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hospedes')
    op.drop_table('reservas')
    op.drop_table('grupo_apartamentos')
    op.drop_table('preco_tabelado')
    op.drop_table('grupos')
    op.drop_table('users')
    op.drop_table('relatorio_reserva')
    op.drop_table('hospedagens')
    op.drop_table('clientes')
    # ### end Alembic commands ###
