"""Adiciona campo data inicio e fim à tabela Preço

Revision ID: c753db40e4e2
Revises: e60424eb2b25
Create Date: 2025-06-25 22:14:56.704472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c753db40e4e2'
down_revision = 'e60424eb2b25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preco_tabelado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_inicio', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('data_fim', sa.Date(), nullable=False))
        batch_op.drop_column('data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preco_tabelado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_column('data_fim')
        batch_op.drop_column('data_inicio')

    # ### end Alembic commands ###
