"""Criação inicial

Revision ID: d3e2cc1aac94
Revises: 
Create Date: 2025-06-25 17:52:25.629674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3e2cc1aac94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_nasc', sa.Date(), nullable=True))

    with op.batch_alter_table('preco_tabelado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preco_tabelado', schema=None) as batch_op:
        batch_op.drop_column('data')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('data_nasc')

    # ### end Alembic commands ###
