"""Aumenta tamanho do id_reserva

Revision ID: de363aeb0549
Revises: 75d9cfe0125b
Create Date: 2025-07-16 22:59:39.319630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de363aeb0549'
down_revision = '75d9cfe0125b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('bairro',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    with op.batch_alter_table('grupo_apartamentos', schema=None) as batch_op:
        batch_op.alter_column('preco',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.alter_column('id_reserva',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=100),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.alter_column('id_reserva',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('grupo_apartamentos', schema=None) as batch_op:
        batch_op.alter_column('preco',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.alter_column('bairro',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###
