"""Adiciona campo Diária de Criança em tabela Reserva

Revision ID: e60424eb2b25
Revises: aeb298d6fee9
Create Date: 2025-06-25 21:26:50.008665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e60424eb2b25'
down_revision = 'aeb298d6fee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diaria_crianca', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservas', schema=None) as batch_op:
        batch_op.drop_column('diaria_crianca')

    # ### end Alembic commands ###
